const dict = {
  北京: 'BeiJing',
  天津: 'TianJin',
  河北: 'HeBei',
  山西: 'ShanXi',
  内蒙古: 'NeiMengGu',
  辽宁: 'LiaoNing',
  吉林: 'JiLin',
  黑龙江: 'HeiLongJiang',
  上海: 'ShangHai',
  江苏: 'JiangSu',
  浙江: 'ZheJiang',
  安徽: 'AnHui',
  福建: 'FuJian',
  江西: 'JiangXi',
  山东: 'ShanDong',
  河南: 'HeNan',
  湖北: 'HuBei',
  湖南: 'HuNan',
  广东: 'GuangDong',
  广西: 'GuangXi',
  海南: 'HaiNan',
  重庆: 'ZhongQing',
  四川: 'SiChuan',
  贵州: 'GuiZhou',
  云南: 'YunNan',
  西藏: 'Xizang',
  陕西: 'ShanXi',
  甘肃: 'GanSu',
  青海: 'QingHai',
  宁夏: 'NingXia',
  新疆: 'XinJiang',
  台湾: 'TaiWan',
  香港: 'xianggang',
  澳门: 'aomen',
}

export { dict }
